name: daily_update_and_publish
on:
    workflow_dispatch:
    schedule:
        - cron: 0 0 * * *
jobs:
    update_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
                  run_install: false
            - uses: actions/cache@v3
              with:
                  path: |
                      '**/node_modules'
                        ~/.npm
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
            - run: pnpm install
            - name: update packages and commit changes
              run: |
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  pnpm run up
            - uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: master
            # - run: pnpm run pub
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
