name: daily_update_and_publish
on:
    schedule:
        - cron: 0 0 * * *
jobs:
    update_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  run_install: false
            - uses: actions/cache@v3
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
            - run: pnpm i
            - run: |
                  git config --local user.name "github-actions[bot]"
                  pnpm run up
            - uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: master
            # - run: pnpm run pub
